#!/bin/bash

#SBATCH --job-name=V10
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --partition=sched_mit_binz
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --constraint=centos7

module load engaging/openmpi/2.0.3


export dir=/home/aplatham2/Programs/gromacs-2018.4/bin
export tabledir=/pool001/aplatham2/ELP/MOFF_tables

$dir/gmx_mpi grompp -f min.mdp -c start.gro -p ELP.top -o min.tpr
$dir/gmx_mpi mdrun -deffnm min -table $tabledir/table_2000MOFF.xvg -tablep $tabledir/table_2000smog.xvg


$dir/gmx_mpi grompp -f eq.mdp -c min.gro -p ELP.top -o eq.tpr  -maxwarn 1
mpirun -np 1 $dir/gmx_mpi mdrun -deffnm eq -dlb yes -table $tabledir/table_2000MOFF.xvg -tablep $tabledir/table_2000smog.xvg -maxh 47.9   -noddcheck -rdd 4
